// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDZyDR9jhce2njKui1Mn5sZ8HCEDHBuAM',
    appId: '1:141469474726:web:70b93f85e8d0dbf09c3967',
    messagingSenderId: '141469474726',
    projectId: 'metafam0',
    authDomain: 'metafam0.firebaseapp.com',
    storageBucket: 'metafam0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBFxIfqhzTZVljzGnONNo-y2tVABHZoTU',
    appId: '1:141469474726:android:95bb3564c27583799c3967',
    messagingSenderId: '141469474726',
    projectId: 'metafam0',
    storageBucket: 'metafam0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcSZkIxgVZoRZ0kgCebYxSTq2Pal_5xuI',
    appId: '1:141469474726:ios:3a9e9cfc60d6eff59c3967',
    messagingSenderId: '141469474726',
    projectId: 'metafam0',
    storageBucket: 'metafam0.appspot.com',
    iosClientId: '141469474726-7lgsr92hln543o4d35epl7ie4f1djftn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcSZkIxgVZoRZ0kgCebYxSTq2Pal_5xuI',
    appId: '1:141469474726:ios:3a9e9cfc60d6eff59c3967',
    messagingSenderId: '141469474726',
    projectId: 'metafam0',
    storageBucket: 'metafam0.appspot.com',
    iosClientId: '141469474726-7lgsr92hln543o4d35epl7ie4f1djftn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
